/* ****************************************************************************
 *
 * Copyright (c) Microsoft Corporation. 
 *
 * This source code is subject to terms and conditions of the Microsoft Public License. A 
 * copy of the license can be found in the License.html file at the root of this distribution. If 
 * you cannot locate the  Microsoft Public License, please send an email to 
 * dlr@microsoft.com. By using this source code in any fashion, you are agreeing to be bound 
 * by the terms of the Microsoft Public License.
 *
 * You must not remove this notice, or any other, from this software.
 *
 *
 * ***************************************************************************/

using Microsoft.Scripting.Actions;
using System.CodeDom.Compiler;

namespace Microsoft.Scripting.Runtime {
    public static partial class RuntimeHelpers {

        #region Generated Dynamic Sites Construction Helpers

        // *** BEGIN GENERATED CODE ***
        // generated by function: gen_construction_helpers from: generate_dynsites.py

        [GeneratedCode("DLR", "2.0")]
        public static DynamicSite<T0, R> CreateSimpleCallSite<T0, R>() {
            return new DynamicSite<T0, R>(CallAction.Make(0));
        }

        [GeneratedCode("DLR", "2.0")]
        public static DynamicSite<T0, T1, R> CreateSimpleCallSite<T0, T1, R>() {
            return new DynamicSite<T0, T1, R>(CallAction.Make(1));
        }

        [GeneratedCode("DLR", "2.0")]
        public static DynamicSite<T0, T1, T2, R> CreateSimpleCallSite<T0, T1, T2, R>() {
            return new DynamicSite<T0, T1, T2, R>(CallAction.Make(2));
        }

        [GeneratedCode("DLR", "2.0")]
        public static DynamicSite<T0, T1, T2, T3, R> CreateSimpleCallSite<T0, T1, T2, T3, R>() {
            return new DynamicSite<T0, T1, T2, T3, R>(CallAction.Make(3));
        }

        [GeneratedCode("DLR", "2.0")]
        public static DynamicSite<T0, T1, T2, T3, T4, R> CreateSimpleCallSite<T0, T1, T2, T3, T4, R>() {
            return new DynamicSite<T0, T1, T2, T3, T4, R>(CallAction.Make(4));
        }

        [GeneratedCode("DLR", "2.0")]
        public static DynamicSite<T0, T1, T2, T3, T4, T5, R> CreateSimpleCallSite<T0, T1, T2, T3, T4, T5, R>() {
            return new DynamicSite<T0, T1, T2, T3, T4, T5, R>(CallAction.Make(5));
        }

        [GeneratedCode("DLR", "2.0")]
        public static FastDynamicSite<T0, R> CreateSimpleCallSite<T0, R>(CodeContext context) {
            return new FastDynamicSite<T0, R>(context, CallAction.Make(0));
        }

        [GeneratedCode("DLR", "2.0")]
        public static FastDynamicSite<T0, T1, R> CreateSimpleCallSite<T0, T1, R>(CodeContext context) {
            return new FastDynamicSite<T0, T1, R>(context, CallAction.Make(1));
        }

        [GeneratedCode("DLR", "2.0")]
        public static FastDynamicSite<T0, T1, T2, R> CreateSimpleCallSite<T0, T1, T2, R>(CodeContext context) {
            return new FastDynamicSite<T0, T1, T2, R>(context, CallAction.Make(2));
        }

        [GeneratedCode("DLR", "2.0")]
        public static FastDynamicSite<T0, T1, T2, T3, R> CreateSimpleCallSite<T0, T1, T2, T3, R>(CodeContext context) {
            return new FastDynamicSite<T0, T1, T2, T3, R>(context, CallAction.Make(3));
        }

        [GeneratedCode("DLR", "2.0")]
        public static FastDynamicSite<T0, T1, T2, T3, T4, R> CreateSimpleCallSite<T0, T1, T2, T3, T4, R>(CodeContext context) {
            return new FastDynamicSite<T0, T1, T2, T3, T4, R>(context, CallAction.Make(4));
        }

        [GeneratedCode("DLR", "2.0")]
        public static FastDynamicSite<T0, T1, T2, T3, T4, T5, R> CreateSimpleCallSite<T0, T1, T2, T3, T4, T5, R>(CodeContext context) {
            return new FastDynamicSite<T0, T1, T2, T3, T4, T5, R>(context, CallAction.Make(5));
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, R>(ref DynamicSite<T0, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(CallAction.Make(0));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, R>(ref DynamicSite<T0, T1, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(CallAction.Make(1));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, R>(ref DynamicSite<T0, T1, T2, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(CallAction.Make(2));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, T3, R>(ref DynamicSite<T0, T1, T2, T3, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(CallAction.Make(3));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, T3, T4, R>(ref DynamicSite<T0, T1, T2, T3, T4, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(CallAction.Make(4));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, T3, T4, T5, R>(ref DynamicSite<T0, T1, T2, T3, T4, T5, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(CallAction.Make(5));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, R>(CodeContext context, ref FastDynamicSite<T0, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(context, CallAction.Make(0));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, R>(CodeContext context, ref FastDynamicSite<T0, T1, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(context, CallAction.Make(1));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, R>(CodeContext context, ref FastDynamicSite<T0, T1, T2, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(context, CallAction.Make(2));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, T3, R>(CodeContext context, ref FastDynamicSite<T0, T1, T2, T3, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(context, CallAction.Make(3));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, T3, T4, R>(CodeContext context, ref FastDynamicSite<T0, T1, T2, T3, T4, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(context, CallAction.Make(4));
            }
        }

        [GeneratedCode("DLR", "2.0")]
        public static void CreateSimpleCallSite<T0, T1, T2, T3, T4, T5, R>(CodeContext context, ref FastDynamicSite<T0, T1, T2, T3, T4, T5, R> site) {
            if (!site.IsInitialized) {
                site.EnsureInitialized(context, CallAction.Make(5));
            }
        }


        // *** END GENERATED CODE ***

        #endregion
    }
}