/* ****************************************************************************
 *
 * Copyright (c) Microsoft Corporation. 
 *
 * This source code is subject to terms and conditions of the Microsoft Public License. A 
 * copy of the license can be found in the License.html file at the root of this distribution. If 
 * you cannot locate the  Microsoft Public License, please send an email to 
 * dlr@microsoft.com. By using this source code in any fashion, you are agreeing to be bound 
 * by the terms of the Microsoft Public License.
 *
 * You must not remove this notice, or any other, from this software.
 *
 *
 * ***************************************************************************/

using System;
using Microsoft.Scripting.Runtime;

namespace Microsoft.Scripting.Actions {
    public static class UpdateDelegates {
        internal static T MakeUpdateDelegate<T>() {
            Type target = typeof(T);

            if (target.IsGenericType) {
                Type generic = target.GetGenericTypeDefinition();
                Type[] gargs = target.GetGenericArguments();
                string method = null;

                switch (gargs.Length) {
                    case 2:
                        if (generic == typeof(DynamicSiteTarget<,>)) {
                            method = "Update1";
                        } else if (generic == typeof(BigDynamicSiteTarget<,>)) {
                            method = "UpdateBig";
                        }
                        break;
                    case 3:
                        if (generic == typeof(DynamicSiteTarget<,,>)) {
                            method = "Update2";
                        }
                        break;
                    case 4:
                        if (generic == typeof(DynamicSiteTarget<,,,>)) {
                            method = "Update3";
                        }
                        break;
                    case 5:
                        if (generic == typeof(DynamicSiteTarget<,,,,>)) {
                            method = "Update4";
                        }
                        break;
                    case 6:
                        if (generic == typeof(DynamicSiteTarget<,,,,,>)) {
                            method = "Update5";
                        }
                        break;
                    case 7:
                        if (generic == typeof(DynamicSiteTarget<,,,,,,>)) {
                            method = "Update6";
                        }
                        break;
                }

                if (method != null) {
                    return (T)(object)Delegate.CreateDelegate(target, typeof(UpdateDelegates).GetMethod(method).MakeGenericMethod(gargs));
                }
            }

            // TODO: Use LCG to create custom update target
            throw new InvalidOperationException("Invalid delegate type for unpdate target");
        }

        #region Generated Predefined Update Targets

        // *** BEGIN GENERATED CODE ***
        // generated by function: gen_update_targets from: generate_dynsites.py

        /// <summary>
        /// Site update code
        /// </summary>
        public static TRet Update1<T0, TRet>(CallSite site, CodeContext context, T0 arg0) {
            CallSite<DynamicSiteTarget<T0, TRet>> s = (CallSite<DynamicSiteTarget<T0, TRet>>)site;
            return (TRet)site.Binder.UpdateSiteAndExecute<DynamicSiteTarget<T0, TRet>>(context, s, new object[] { arg0 });
        }

        /// <summary>
        /// Site update code
        /// </summary>
        public static TRet Update2<T0, T1, TRet>(CallSite site, CodeContext context, T0 arg0, T1 arg1) {
            CallSite<DynamicSiteTarget<T0, T1, TRet>> s = (CallSite<DynamicSiteTarget<T0, T1, TRet>>)site;
            return (TRet)site.Binder.UpdateSiteAndExecute<DynamicSiteTarget<T0, T1, TRet>>(context, s, new object[] { arg0, arg1 });
        }

        /// <summary>
        /// Site update code
        /// </summary>
        public static TRet Update3<T0, T1, T2, TRet>(CallSite site, CodeContext context, T0 arg0, T1 arg1, T2 arg2) {
            CallSite<DynamicSiteTarget<T0, T1, T2, TRet>> s = (CallSite<DynamicSiteTarget<T0, T1, T2, TRet>>)site;
            return (TRet)site.Binder.UpdateSiteAndExecute<DynamicSiteTarget<T0, T1, T2, TRet>>(context, s, new object[] { arg0, arg1, arg2 });
        }

        /// <summary>
        /// Site update code
        /// </summary>
        public static TRet Update4<T0, T1, T2, T3, TRet>(CallSite site, CodeContext context, T0 arg0, T1 arg1, T2 arg2, T3 arg3) {
            CallSite<DynamicSiteTarget<T0, T1, T2, T3, TRet>> s = (CallSite<DynamicSiteTarget<T0, T1, T2, T3, TRet>>)site;
            return (TRet)site.Binder.UpdateSiteAndExecute<DynamicSiteTarget<T0, T1, T2, T3, TRet>>(context, s, new object[] { arg0, arg1, arg2, arg3 });
        }

        /// <summary>
        /// Site update code
        /// </summary>
        public static TRet Update5<T0, T1, T2, T3, T4, TRet>(CallSite site, CodeContext context, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) {
            CallSite<DynamicSiteTarget<T0, T1, T2, T3, T4, TRet>> s = (CallSite<DynamicSiteTarget<T0, T1, T2, T3, T4, TRet>>)site;
            return (TRet)site.Binder.UpdateSiteAndExecute<DynamicSiteTarget<T0, T1, T2, T3, T4, TRet>>(context, s, new object[] { arg0, arg1, arg2, arg3, arg4 });
        }

        /// <summary>
        /// Site update code
        /// </summary>
        public static TRet Update6<T0, T1, T2, T3, T4, T5, TRet>(CallSite site, CodeContext context, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5) {
            CallSite<DynamicSiteTarget<T0, T1, T2, T3, T4, T5, TRet>> s = (CallSite<DynamicSiteTarget<T0, T1, T2, T3, T4, T5, TRet>>)site;
            return (TRet)site.Binder.UpdateSiteAndExecute<DynamicSiteTarget<T0, T1, T2, T3, T4, T5, TRet>>(context, s, new object[] { arg0, arg1, arg2, arg3, arg4, arg5 });
        }

        /// <summary>
        /// Site update code
        /// </summary>
        public static TRet UpdateBig<T0, TRet>(CallSite site, CodeContext context, T0 arg0) where T0 : Tuple {
            CallSite<BigDynamicSiteTarget<T0, TRet>> s = (CallSite<BigDynamicSiteTarget<T0, TRet>>)site;
            return (TRet)site.Binder.UpdateSiteAndExecute<BigDynamicSiteTarget<T0, TRet>>(context, s, Tuple.GetTupleValues(arg0));
        }


        // *** END GENERATED CODE ***

        #endregion
    }
}
