/* ****************************************************************************
 *
 * Copyright (c) Microsoft Corporation. 
 *
 * This source code is subject to terms and conditions of the Microsoft Public License. A 
 * copy of the license can be found in the License.html file at the root of this distribution. If 
 * you cannot locate the  Microsoft Public License, please send an email to 
 * dlr@microsoft.com. By using this source code in any fashion, you are agreeing to be bound 
 * by the terms of the Microsoft Public License.
 *
 * You must not remove this notice, or any other, from this software.
 *
 *
 * ***************************************************************************/

namespace Microsoft.Scripting.Ast {
    /// <summary>
    /// Walker class - The DLR AST Walker
    /// </summary>
    partial class Walker {

        #region Generated DLR AST Walker

        // *** BEGIN GENERATED CODE ***
        // generated by function: gen_scripting_walker from: generate_tree.py

        // ActionExpression
        protected internal virtual bool Walk(ActionExpression node) { return true; }
        protected internal virtual void PostWalk(ActionExpression node) { }

        // AssignmentExpression
        protected internal virtual bool Walk(AssignmentExpression node) { return true; }
        protected internal virtual void PostWalk(AssignmentExpression node) { }

        // BinaryExpression
        protected internal virtual bool Walk(BinaryExpression node) { return true; }
        protected internal virtual void PostWalk(BinaryExpression node) { }

        // Block
        protected internal virtual bool Walk(Block node) { return true; }
        protected internal virtual void PostWalk(Block node) { }

        // BreakStatement
        protected internal virtual bool Walk(BreakStatement node) { return true; }
        protected internal virtual void PostWalk(BreakStatement node) { }

        // ConditionalExpression
        protected internal virtual bool Walk(ConditionalExpression node) { return true; }
        protected internal virtual void PostWalk(ConditionalExpression node) { }

        // ConstantExpression
        protected internal virtual bool Walk(ConstantExpression node) { return true; }
        protected internal virtual void PostWalk(ConstantExpression node) { }

        // ContinueStatement
        protected internal virtual bool Walk(ContinueStatement node) { return true; }
        protected internal virtual void PostWalk(ContinueStatement node) { }

        // DeleteStatement
        protected internal virtual bool Walk(DeleteStatement node) { return true; }
        protected internal virtual void PostWalk(DeleteStatement node) { }

        // DoStatement
        protected internal virtual bool Walk(DoStatement node) { return true; }
        protected internal virtual void PostWalk(DoStatement node) { }

        // EmptyStatement
        protected internal virtual bool Walk(EmptyStatement node) { return true; }
        protected internal virtual void PostWalk(EmptyStatement node) { }

        // GeneratorLambdaExpression
        protected internal virtual bool Walk(GeneratorLambdaExpression node) { return true; }
        protected internal virtual void PostWalk(GeneratorLambdaExpression node) { }

        // IntrinsicExpression
        protected internal virtual bool Walk(IntrinsicExpression node) { return true; }
        protected internal virtual void PostWalk(IntrinsicExpression node) { }

        // InvocationExpression
        protected internal virtual bool Walk(InvocationExpression node) { return true; }
        protected internal virtual void PostWalk(InvocationExpression node) { }

        // LabeledStatement
        protected internal virtual bool Walk(LabeledStatement node) { return true; }
        protected internal virtual void PostWalk(LabeledStatement node) { }

        // LambdaExpression
        protected internal virtual bool Walk(LambdaExpression node) { return true; }
        protected internal virtual void PostWalk(LambdaExpression node) { }

        // LoopStatement
        protected internal virtual bool Walk(LoopStatement node) { return true; }
        protected internal virtual void PostWalk(LoopStatement node) { }

        // MemberExpression
        protected internal virtual bool Walk(MemberExpression node) { return true; }
        protected internal virtual void PostWalk(MemberExpression node) { }

        // MethodCallExpression
        protected internal virtual bool Walk(MethodCallExpression node) { return true; }
        protected internal virtual void PostWalk(MethodCallExpression node) { }

        // NewArrayExpression
        protected internal virtual bool Walk(NewArrayExpression node) { return true; }
        protected internal virtual void PostWalk(NewArrayExpression node) { }

        // NewExpression
        protected internal virtual bool Walk(NewExpression node) { return true; }
        protected internal virtual void PostWalk(NewExpression node) { }

        // ParameterExpression
        protected internal virtual bool Walk(ParameterExpression node) { return true; }
        protected internal virtual void PostWalk(ParameterExpression node) { }

        // ReturnStatement
        protected internal virtual bool Walk(ReturnStatement node) { return true; }
        protected internal virtual void PostWalk(ReturnStatement node) { }

        // ScopeStatement
        protected internal virtual bool Walk(ScopeStatement node) { return true; }
        protected internal virtual void PostWalk(ScopeStatement node) { }

        // SwitchStatement
        protected internal virtual bool Walk(SwitchStatement node) { return true; }
        protected internal virtual void PostWalk(SwitchStatement node) { }

        // ThrowStatement
        protected internal virtual bool Walk(ThrowStatement node) { return true; }
        protected internal virtual void PostWalk(ThrowStatement node) { }

        // TryStatement
        protected internal virtual bool Walk(TryStatement node) { return true; }
        protected internal virtual void PostWalk(TryStatement node) { }

        // TypeBinaryExpression
        protected internal virtual bool Walk(TypeBinaryExpression node) { return true; }
        protected internal virtual void PostWalk(TypeBinaryExpression node) { }

        // UnaryExpression
        protected internal virtual bool Walk(UnaryExpression node) { return true; }
        protected internal virtual void PostWalk(UnaryExpression node) { }

        // VariableExpression
        protected internal virtual bool Walk(VariableExpression node) { return true; }
        protected internal virtual void PostWalk(VariableExpression node) { }

        // YieldStatement
        protected internal virtual bool Walk(YieldStatement node) { return true; }
        protected internal virtual void PostWalk(YieldStatement node) { }

        // CatchBlock
        protected internal virtual bool Walk(CatchBlock node) { return true; }
        protected internal virtual void PostWalk(CatchBlock node) { }

        // IfStatementTest
        protected internal virtual bool Walk(IfStatementTest node) { return true; }
        protected internal virtual void PostWalk(IfStatementTest node) { }

        // SwitchCase
        protected internal virtual bool Walk(SwitchCase node) { return true; }
        protected internal virtual void PostWalk(SwitchCase node) { }

        // *** END GENERATED CODE ***

        #endregion

    }
}
