/* ****************************************************************************
 *
 * Copyright (c) Microsoft Corporation. 
 *
 * This source code is subject to terms and conditions of the Microsoft Permissive License. A 
 * copy of the license can be found in the License.html file at the root of this distribution. If 
 * you cannot locate the  Microsoft Permissive License, please send an email to 
 * ironpy@microsoft.com. By using this source code in any fashion, you are agreeing to be bound 
 * by the terms of the Microsoft Permissive License.
 *
 * You must not remove this notice, or any other, from this software.
 *
 *
 * ***************************************************************************/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Scripting.Internal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Scripting.InternalResources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t assign to {0}.
        /// </summary>
        internal static string CantAssign {
            get {
                return ResourceManager.GetString("CantAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t perform deletion.
        /// </summary>
        internal static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t read from property.
        /// </summary>
        internal static string CantReadProperty {
            get {
                return ResourceManager.GetString("CantReadProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t write to property.
        /// </summary>
        internal static string CantWriteProperty {
            get {
                return ResourceManager.GetString("CantWriteProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... .
        /// </summary>
        internal static string ConsoleContinuePrompt {
            get {
                return ResourceManager.GetString("ConsoleContinuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; .
        /// </summary>
        internal static string ConsolePrompt {
            get {
                return ResourceManager.GetString("ConsolePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected SymbolId, got SymbolId.Empty.
        /// </summary>
        internal static string EmptySymbolId {
            get {
                return ResourceManager.GetString("EmptySymbolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create instance of {0} because it contains generic parameters.
        /// </summary>
        internal static string IllegalNew_GenericParams {
            get {
                return ResourceManager.GetString("IllegalNew_GenericParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to define parameter on non-methodbuilder and non-dynamic method.
        /// </summary>
        internal static string InvalidOperation_DefineParameterBakedMethod {
            get {
                return ResourceManager.GetString("InvalidOperation_DefineParameterBakedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setting this.
        /// </summary>
        internal static string InvalidOperation_SetThis {
            get {
                return ResourceManager.GetString("InvalidOperation_SetThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emitting this in static method.
        /// </summary>
        internal static string InvalidOperation_ThisInStaticMethod {
            get {
                return ResourceManager.GetString("InvalidOperation_ThisInStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too many arguments.
        /// </summary>
        internal static string InvalidOperation_TooManyArguments {
            get {
                return ResourceManager.GetString("InvalidOperation_TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected type, expected {0}, got {1}.
        /// </summary>
        internal static string InvalidOperation_UnexpectedType {
            get {
                return ResourceManager.GetString("InvalidOperation_UnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign: {0}.
        /// </summary>
        internal static string NotImplemented_Assign {
            get {
                return ResourceManager.GetString("NotImplemented_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot emit raw enum value for type {0} with value {1}.
        /// </summary>
        internal static string NotImplemented_EnumEmit {
            get {
                return ResourceManager.GetString("NotImplemented_EnumEmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate: {0}.
        /// </summary>
        internal static string NotImplemented_Evaluate {
            get {
                return ResourceManager.GetString("NotImplemented_Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute: {0}.
        /// </summary>
        internal static string NotImplemented_Execute {
            get {
                return ResourceManager.GetString("NotImplemented_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-verifiable assembly generated: {0}:\nAssembly preserved as {1}\nError text:\n{2}\n.
        /// </summary>
        internal static string VerificationException {
            get {
                return ResourceManager.GetString("VerificationException", resourceCulture);
            }
        }
    }
}
